services:
  mongodb:
   image: mongo:7.0.16
   restart: always
   ports: 
    - "27017:27017"
   env_file:
    - ./.env 
   environment:
          MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
          MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
   volumes: 
       - mongodb-data:/data/db
   networks:
    backend-task:


  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/
    networks:
     backend-task:
 


volumes: 
    mongodb-data:

networks:
   backend-task:
    name: backend-task-network
    driver: bridge